# **Assignment 7**

Pawan Kumar : 224230                          
Raj Rajeshwari Prasad: 224237                        
Sesha Sai Kiran Bhavaraju : 224160

# **Importing Libraries**

In [0]:
%tensorflow_version 2.x
from tensorflow.keras import backend as K
from random import randint
import tensorflow as tf
import numpy as np

# **Task 1**

In [0]:
@tf.function
def Task1(n):
  t1 = tf.random.normal(shape = (10,n), mean = 0, stddev=50, dtype=tf.dtypes.float32, seed = None)
  t2 = tf.math.top_k(t1,k = 1, sorted= True)

  print(t2)

  return(t2)


In [22]:
Task1(5)

TopKV2(values=<tf.Tensor 'TopKV2:0' shape=(10, 1) dtype=float32>, indices=<tf.Tensor 'TopKV2:1' shape=(10, 1) dtype=int32>)


TopKV2(values=<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 90.622086],
       [ 60.010403],
       [ 93.32705 ],
       [ 64.12159 ],
       [ 47.7884  ],
       [ 64.97065 ],
       [ 37.2147  ],
       [ 67.21049 ],
       [-19.81553 ],
       [ 61.401974]], dtype=float32)>, indices=<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[0],
       [4],
       [1],
       [1],
       [4],
       [3],
       [3],
       [2],
       [0],
       [0]], dtype=int32)>)

# **Task 2**

In [0]:
def Task2(n):
  #tensor_temp = tf.constant([])
  t1 =  tf.random.normal(shape = (10,n), mean = 0, stddev=50, dtype=tf.dtypes.float32, seed = None)
  #t2 = tf.clip_by_norm(t1, clip_norm=)
  t11 = []
  rows = tf.split(t1, num_or_size_splits= len(t1))
  for each in rows:
    temp = K.cast(K.equal(each,K.max(each)), dtype=tf.dtypes.float32)
    #tensor1 = tf.concat(temp, 0)
    t11 += [temp]

  return t11


In [24]:
Task2(5)

[<tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 1., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 0., 1., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[1., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[1., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 1., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[1., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[0., 0., 0., 0., 1.]], dtype=float32)>]

# **Task 3**

In [25]:
def task_3():
  k = 2
  n = 5
  inp = np.random.random((10,n))
  input_tensor = tf.convert_to_tensor(inp)
  inp.sort(axis = 0)
  high_value,index = tf.nn.top_k(input_tensor, k =k)
  output_tensor = tf.Variable(tf.zeros_like(input_tensor))
  for ind in range(input_tensor.shape[0]):
    for val in index[ind]:
      output_tensor = (output_tensor[ind, val]).assign(input_tensor[ind,val])
  
  tf.print("Input Tensor: ", input_tensor)
  tf.print("Output: ", output_tensor)

task_3()

Input Tensor:  [[0.048062680069608787 0.023018879471889853 0.20605197877134529 0.011468678085643114 0.061715629251836379]
 [0.14586233428591211 0.044847223870031927 0.20752788066358308 0.046045798097338664 0.14717522488084978]
 [0.21708793109058855 0.079896759005308793 0.36277773572305572 0.10988353342597212 0.29596725004575686]
 ...
 [0.782013187926065 0.47841299100901824 0.70831958047800869 0.72484901597050777 0.90231834053599791]
 [0.90957492351875169 0.61775058659050119 0.76531635223378558 0.85319511719407126 0.96846257153731241]
 [0.92496402733894711 0.86113489293467727 0.96301611392929232 0.92391386422181843 0.9894031681637353]]
Output:  [[0 0 0.20605197877134529 0 0.061715629251836379]
 [0 0 0.20752788066358308 0 0.14717522488084978]
 [0 0 0.36277773572305572 0 0.29596725004575686]
 ...
 [0.782013187926065 0 0 0 0.90231834053599791]
 [0.90957492351875169 0 0 0 0.96846257153731241]
 [0 0 0.96301611392929232 0 0.9894031681637353]]


# **Task 4**

In [26]:
n = 5
inp_tensor = tf.Variable(tf.random.normal([n], mean = 0, stddev=50, dtype=tf.dtypes.float32, seed = None))
new_tensor = tf.Variable(tf.zeros_like(inp_tensor))

def task4():
  global inp_tensor, new_tensor
  a =5
  print('Input Tensor: '+ str(inp_tensor))
  for i in range(1, inp_tensor.shape[0]):
    new_tensor = inp_tensor[i].assign(a * new_tensor[i-1] + (1-a) * inp_tensor[i])
  print('New Tensor : ' + str(new_tensor))

task4()

Input Tensor: <tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=
array([ 20.346237, -27.820286, -17.491646, -63.797997, -27.917046],
      dtype=float32)>
New Tensor : <tf.Variable 'UnreadVariable' shape=(5,) dtype=float32, numpy=
array([   20.346237,   111.28114 ,   626.3723  ,  3387.0535  ,
       17046.936   ], dtype=float32)>


# **Task 5**

In [27]:
new_tensor[-1]

<tf.Tensor: shape=(), dtype=float32, numpy=17046.936>

# **Task 6**

In [28]:
def task6():
  x = tf.random.uniform(shape=([5]), maxval=20,dtype=tf.dtypes.int32)
  y = tf.random.uniform(shape=([5]), maxval=20,dtype=tf.dtypes.int32)
  z = tf.random.uniform(shape=([5]), maxval=20,dtype=tf.dtypes.int32)
  print('X : ' + str(x))
  print('Y : ' + str(y))
  print('Z : ' + str(z))
  new = tf.Variable(tf.zeros_like(x))

  for i in range(0, x.shape[0]):
    if x[i]%2 ==0:
      new[i].assign(y[i]) 
    else:
      new[i].assign(z[i])
  print(new)

task6()



X : tf.Tensor([ 4  9  9  0 17], shape=(5,), dtype=int32)
Y : tf.Tensor([14  2 13  9 11], shape=(5,), dtype=int32)
Z : tf.Tensor([16 16 19  8  0], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([14, 16, 19,  9,  0], dtype=int32)>


# **Task7**

In [0]:
def task7():
  n = randint(0,150)
  x = tf.random.uniform(shape=([n,n]), maxval=20,dtype=tf.dtypes.int32)
  #dim_val = x.shape[0]
  if tf.size(x[-1])>100:
    return 100
  elif tf.size(x[-1])<=100 and tf.size(x[-1])>44:
    return 12
  else:
    return 0

In [30]:
task7()

100

# **Task8**

In [0]:
count1, count2, count3 = 0,0,0

def task8():
  global count1, count2, count3
  n = randint(0,150)
  x = tf.random.uniform(shape=([n,n]), maxval=20,dtype=tf.dtypes.int32)
  #count1 += 1 if len(x[-1])>100 else 0
  if len(x[-1])>100:
    count1 = count1 + 1
    return 100
  elif len(x[-1])<=100 and len(x[-1])>44:
    count2 = count2 +1
    return 12
  else:
    count3 = count3 +1
  return 0

In [32]:
for i in range(10):
  task8()

print('count1: {}'.format(count1))
print('count2: {}'.format(count2))
print('count3: {}'.format(count3))

count1: 6
count2: 2
count3: 2


# **Task9**

In [33]:
@tf.function
def task9(t1, t2):
  global ret_tensor
  n=len(t1[0])
  res=tf.zeros([n,n])
  t1=tf.broadcast_to(t1,[n,n])
  t2=tf.broadcast_to(t2,[n,n])
  t3=tf.subtract(t1,tf.transpose(t2))
  tf.print(t3)

ret_tensor = []
t_one = tf.random.uniform(shape=(1,5),maxval=20, dtype=tf.dtypes.int32) 
t_two = tf.random.uniform(shape=(1,5),maxval=20, dtype=tf.dtypes.int32)
task9(t_one, t_two)

[[4 4 -7 -9 0]
 [0 0 -11 -13 -4]
 [0 0 -11 -13 -4]
 [11 11 0 -2 7]
 [18 18 7 5 14]]


# **Task10**

In [34]:
def task10():
  h = tf.random.uniform([1,4,3])# batch  x time x features(vocab)
  s = tf.random.uniform([1,3]) # batch x features
  for batch_idx in range(0, len(h)):
    #batch_level_control
    batch = h[batch_idx]
    tensor_lis = []
    for each_tensor in batch:
      #time_level_control
      m1 = tf.constant(tf.matmul(tf.reshape(each_tensor, (1,3)),tf.transpose(s)))
      tensor_lis += [m1]    
    print(tensor_lis)
task10()

[<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.65647393]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.09668623]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.03610782]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.03396068]], dtype=float32)>]
